config/routes.rb
BasicProjects::Engine.routes.draw do

  resources :projects
  resources :categories
  root 'projects#index'
end

app/models/basic_projects/category.rb
module BasicProjects
  class Category < ActiveRecord::Base
    extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]
    has_many :projects
    validates_presence_of :title, :description, :slug

  end
end

app/models/basic_projects/project.rb
module BasicProjects
  class Project < ActiveRecord::Base
    belongs_to :category
    extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]
    mount_uploader :image, ImageUploader
    validates_presence_of :title, :description, :slug, :category
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/controllers/basic_projects/application_controller.rb
module BasicProjects
  class ApplicationController < ActionController::Base
    layout 'layouts/application'

  end
end

app/controllers/basic_projects/categories_controller.rb
require_dependency "basic_projects/application_controller"

module BasicProjects
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show]

    # GET /categories
    def index
      @categories = Category.page(params[:page])
    end

    # GET /categories/1
    def show
    end


    private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:title, :description, :slug)
    end
  end
end

app/controllers/basic_projects/projects_controller.rb
require_dependency "basic_projects/application_controller"

module BasicProjects
  class ProjectsController < ApplicationController
    before_action :set_project, only: [:show]

    # GET /books
    def index
      @projects = Project.page(params[:page])
    end

    # GET /books/1
    def show
    end


    private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :lead, :excerpt, :description, :content, :project_link, :image, :slug, :category_id, :position)
    end
  end
end

app/helpers/basic_projects/application_helper.rb
module BasicProjects
  module ApplicationHelper
  end
end

app/helpers/basic_projects/categories_helper.rb
module BasicProjects
  module CategoriesHelper
  end
end

app/helpers/basic_projects/projects_helper.rb
module BasicProjects
  module ProjectsHelper
    def show_project_bg(project)
      if project.image.blank?
        #FIXME... static image
        "background-image: url('#{image_path "basic_project/post-thumb03.jpg"}')"
      else
        "background-image: url('#{project.image_url(:thumb)}')"
      end
    end
  end
end

app/views/basic_projects/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><%= category.slug %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/basic_projects/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @category.slug %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/basic_projects/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Lead</th>
      <th>Excerpt</th>
      <th>Description</th>
      <th>Content</th>
      <th>Project link</th>
      <th>Image</th>
      <th>Slug</th>
      <th>Category</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.lead %></td>
        <td><%= project.excerpt %></td>
        <td><%= project.description %></td>
        <td><%= project.content %></td>
        <td><%= project.project_link %></td>
        <td><%= project.image %></td>
        <td><%= project.slug %></td>
        <td><%= project.category %></td>
        <td><%= project.position %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/basic_projects/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Lead:</strong>
  <%= @project.lead %>
</p>

<p>
  <strong>Excerpt:</strong>
  <%= @project.excerpt %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Content:</strong>
  <%= @project.content %>
</p>

<p>
  <strong>Project link:</strong>
  <%= @project.project_link %>
</p>

<p>
  <strong>Image:</strong>
  <%= @project.image %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @project.slug %>
</p>

<p>
  <strong>Category:</strong>
  <%= @project.category %>
</p>

<p>
  <strong>Position:</strong>
  <%= @project.position %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/layouts/basic_projects/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->
  <%= stylesheet_link_tag    "basic_projects/application", media: "all" %>
  <%= javascript_include_tag "basic_projects/application" %>

  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Project name", "#", class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
      <% end %>
  <% end %>

  <%= yield %>
</div>
</body>
</html>